### ISSUE TITLE
Node Performance

### ISSUE THREAD

**Issue by Anyman-Tester** [GalaxyPay/avm-win-node#20]
New to running a validator node so I am not sure what is consider normal or an issue.

How long was your node running with 37K Algos to produce 391 proposed blocks and vote on 169580 blocks, based on your example picture?

Additional Note: I enabled the P2P option in the config tab

**Comment by acfunk** [comment]
That account has been participating (with a varying amount of Algo) for 2 years. Calculating your odds of voting/proposing is a dynamic thing as it depends on the amount of stake currently online. If you want to monitor your nodes performance, I recommend https://alerts.allo.info/

P2P is a newish setting that allows you to connect to other participation nodes rather than relays. Hybrid allows both types of connections. That _shouldn't_ affect your node's performance. If you are interested in seeing what peers you are connected to, you can run the `p2p` build of the node binaries.

![Screenshot 2024-11-16 133103](https://github.com/user-attachments/assets/b597dba5-cc0b-4768-b360-718b91fbd7f6)

**Comment by Anyman-Tester** [comment]
Looking at your numbers now gives me a good general perspective and puts you roughly 1 block every two days on avg. 

As always, super helpful and great work.
